Repository Like-House/BE, pull requests merged in 2024-07, with the labels that each got.

#3 👷 Ci : ci/cd 설정
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/backend/like_house/global/common/RootController.java
  src/main/resources/application-database.yml
  src/main/resources/application-jwt.yml
Labels: :construction_worker: ci

#4 🐛 Fix: DB 연결 수정 및 health check url 열기
  src/main/java/backend/like_house/global/redis/RedisConfig.java
  src/main/java/backend/like_house/global/security/SecurityConfig.java
  src/main/resources/application-database.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: :bug: bug

#5 ✨ Feature : Entity Mapping
  src/main/java/backend/like_house/domain/account/entity/BlockUser.java
  src/main/java/backend/like_house/domain/account/entity/Contact.java
  src/main/java/backend/like_house/domain/account/entity/Custom.java
  src/main/java/backend/like_house/domain/chatting/entity/Chat.java
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
  src/main/java/backend/like_house/domain/chatting/entity/UserChatRoom.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilyEmoticon.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilySpace.java
  src/main/java/backend/like_house/domain/notification/entity/Notification.java
  src/main/java/backend/like_house/domain/post/entity/Comment.java
  src/main/java/backend/like_house/domain/post/entity/Post.java
  src/main/java/backend/like_house/domain/post/entity/PostImage.java
  src/main/java/backend/like_house/domain/post/entity/PostLike.java
  src/main/java/backend/like_house/domain/post/entity/UserPostTag.java
  src/main/java/backend/like_house/domain/schedule/entity/Schedule.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/global/common/BaseEntity.java
  src/main/java/backend/like_house/global/common/enums/ChatRoomType.java
  src/main/java/backend/like_house/global/common/enums/NotificationType.java
  src/main/java/backend/like_house/global/common/enums/ScheduleType.java
  src/main/java/backend/like_house/global/redis/RedisConfig.java
Labels: :sparkles: feature

#7 🐛 Fix : Access to /v3/api-docs/**
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :bug: bug

#14 ✨ Feature : 회원가입/로그인 구현
  .gitignore
  build.gradle
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/converter/AuthConverter.java
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/auth/repository/AuthRepository.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/code/status/SuccessStatus.java
  src/main/java/backend/like_house/global/error/handler/AuthException.java
  src/main/java/backend/like_house/global/redis/Redis.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
  src/main/java/backend/like_house/global/security/SecurityConfig.java
  src/main/java/backend/like_house/global/security/annotation/LoginUser.java
  src/main/java/backend/like_house/global/security/annotation/LoginUserResolver.java
  src/main/java/backend/like_house/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/backend/like_house/global/security/exception/JwtAuthenticationEntryPoint.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/backend/like_house/global/security/filter/JwtExceptionFilter.java
  src/main/java/backend/like_house/global/security/principal/CustomUserDetails.java
  src/main/java/backend/like_house/global/security/principal/CustomUserDetailsService.java
  src/main/java/backend/like_house/global/security/util/JWTUtil.java
  src/main/java/backend/like_house/global/security/util/ResponseUtil.java
  src/main/resources/application-jwt.yml
Labels: :sparkles: feature

#21 📝 Docs : 서비스 이용 Swagger
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilySpaceConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilySpaceDTO.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilySpace.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#24 📝 Docs : 일정 공유 Swagger
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/schedule/dto/ScheduleDTO.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#30 🐛 Bug : LoginResponse의 refreshToken이 null로 반환되는 문제 해결
  src/main/java/backend/like_house/domain/auth/converter/AuthConverter.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
Labels: :bug: bug

#27 📝 Docs : Auth 관련 Swagger
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/code/status/SuccessStatus.java
Labels: :memo: docs

#20 📝 Docs : 채팅 관련 swagger
  src/main/java/backend/like_house/domain/chatting/controller/ChatController.java
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatDTO.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#36 📝 Docs : 유저 정보 설정 Swagger
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
Labels: :memo: docs

#38 ✨ Feature : chatting, 가족 이모티콘 관련 erd 수정
  src/main/java/backend/like_house/domain/chatting/entity/Chat.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilyEmoticon.java
  src/main/java/backend/like_house/domain/post/entity/PostImage.java
Labels: :sparkles: feature, :recycle: refactor

#31 📝 Docs : 가족 목록 Swagger
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilySpaceConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilySpaceDTO.java
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/schedule/dto/ScheduleDTO.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/dto/UserManagementDTO.java
  src/main/java/backend/like_house/domain/user_management/entity/BlockUser.java
  src/main/java/backend/like_house/domain/user_management/entity/Contact.java
  src/main/java/backend/like_house/domain/user_management/entity/Custom.java
Labels: :memo: docs

#35 📝 Docs : Presigned url 관련 swagger
  src/main/java/backend/like_house/global/s3/controller/S3Controller.java
  src/main/java/backend/like_house/global/s3/dto/AwsDTO.java
Labels: :memo: docs

#33 :memo: Docs : 가족 이모 티콘 관련 swagger 작성
  src/main/java/backend/like_house/domain/family_space/controller/FamilyEmoticonController.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilyEmoticonDTO.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#39 📝 Docs : 설정 및 관리 Swagger
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilySpaceConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilySpaceDTO.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilySpace.java
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#19 ✨ Feature : S3 설정
  build.gradle
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/exception/FileConversionException.java
  src/main/java/backend/like_house/global/s3/S3Config.java
  src/main/java/backend/like_house/global/s3/S3Manager.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#47 ♻️ Refactor : accessToken 유효기간 변경
  src/main/resources/application-jwt.yml
Labels: :recycle: refactor

#45 ✨ Feature : 가족 해제 관련 테이블 추가
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/code/status/RemoveUser.java
Labels: :sparkles: feature

#26 📝 Docs : 가족 앨범 Swagger
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/backend/like_house/domain/post/controller/CommentController.java
  src/main/java/backend/like_house/domain/post/controller/FamilyAlbumController.java
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/converter/CommentConverter.java
  src/main/java/backend/like_house/domain/post/converter/FamilyAlbumConverter.java
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/CommentDTO.java
  src/main/java/backend/like_house/domain/post/dto/FamilyAlbumDTO.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/service/CommentCommandService.java
  src/main/java/backend/like_house/domain/post/service/CommentQueryService.java
  src/main/java/backend/like_house/domain/post/service/FamilyAlbumQueryService.java
  src/main/java/backend/like_house/domain/post/service/PostCommandService.java
  src/main/java/backend/like_house/domain/post/service/PostQueryService.java
  src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/CommentQueryServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/FamilyAlbumQueryServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :memo: docs

#51 ✨ Feature : 가족 공간 기능 구현
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilySpaceConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilySpaceDTO.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilySpace.java
  src/main/java/backend/like_house/domain/family_space/repository/FamilySpaceRepository.java
  src/main/java/backend/like_house/domain/family_space/repository/querydsl/FamilySpaceQueryRepository.java
  src/main/java/backend/like_house/domain/family_space/repository/querydsl/impl/FamilySpaceQueryRepositoryImpl.java
  src/main/java/backend/like_house/domain/family_space/service/FamilySpaceCommandService.java
  src/main/java/backend/like_house/domain/family_space/service/FamilySpaceQueryService.java
  src/main/java/backend/like_house/domain/family_space/service/impl/FamilySpaceCommandServiceImpl.java
  src/main/java/backend/like_house/domain/family_space/service/impl/FamilySpaceQueryServiceImpl.java
  src/main/java/backend/like_house/domain/notification/entity/Notification.java
  src/main/java/backend/like_house/domain/post/entity/Post.java
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/entity/Contact.java
  src/main/java/backend/like_house/domain/user_management/entity/RemoveUser.java
  src/main/java/backend/like_house/domain/user_management/repository/BlockUserRepository.java
  src/main/java/backend/like_house/domain/user_management/service/BlockUserQueryService.java
  src/main/java/backend/like_house/domain/user_management/service/impl/BlockUserQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
  src/main/java/backend/like_house/global/validation/annotation/ExistFamilySpace.java
  src/main/java/backend/like_house/global/validation/annotation/HasFamilySpaceUser.java
  src/main/java/backend/like_house/global/validation/annotation/HasNotFamilySpaceUser.java
  src/main/java/backend/like_house/global/validation/annotation/IsRoomManager.java
  src/main/java/backend/like_house/global/validation/annotation/NotBlockedUser.java
  src/main/java/backend/like_house/global/validation/validator/FamilySpaceExistValidator.java
  src/main/java/backend/like_house/global/validation/validator/UserHasFamilySpaceValidator.java
  src/main/java/backend/like_house/global/validation/validator/UserHasNotFamilySpaceValidator.java
  src/main/java/backend/like_house/global/validation/validator/UserIsRoomManagerValidator.java
  src/main/java/backend/like_house/global/validation/validator/UserNotBlockedValidator.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#53 📝 Docs : member error swagger 삭제
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
Labels: :memo: docs

#55 ♻️ Refactor - 가족 공간 삭제시 query 줄이기
  src/main/java/backend/like_house/domain/chatting/entity/Chat.java
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
  src/main/java/backend/like_house/domain/chatting/entity/UserChatRoom.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilyEmoticon.java
  src/main/java/backend/like_house/domain/family_space/entity/FamilySpace.java
  src/main/java/backend/like_house/domain/notification/entity/Notification.java
  src/main/java/backend/like_house/domain/post/entity/Comment.java
  src/main/java/backend/like_house/domain/post/entity/Post.java
  src/main/java/backend/like_house/domain/post/entity/PostImage.java
  src/main/java/backend/like_house/domain/post/entity/PostLike.java
  src/main/java/backend/like_house/domain/post/entity/UserPostTag.java
  src/main/java/backend/like_house/domain/schedule/entity/Schedule.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/domain/user_management/entity/BlockUser.java
  src/main/java/backend/like_house/domain/user_management/entity/Contact.java
  src/main/java/backend/like_house/domain/user_management/entity/Custom.java
  src/main/java/backend/like_house/domain/user_management/entity/RemoveUser.java
Labels: :recycle: refactor

#58 🐛 Fix : CORS Error 해결
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :bug: bug

#50 📝 Docs : 알림 끄기/켜기 Swagger
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/entity/Comment.java
  src/main/java/backend/like_house/domain/post/entity/Post.java
  src/main/java/backend/like_house/domain/post/service/PostCommandService.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
Labels: :memo: docs

#60 📝 Docs : 좋아요 누르기/취소하기 Swagger
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/service/PostCommandService.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
Labels: :memo: docs

#67 🐛 Fix : postController 오류 해결
  src/main/java/backend/like_house/domain/post/controller/PostController.java
Labels: :bug: bug

#63 ✨ Feature - 소셜로그인 구현
  build.gradle
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/converter/AuthConverter.java
  src/main/java/backend/like_house/domain/auth/repository/AuthRepository.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/entity/Role.java
  src/main/java/backend/like_house/domain/user/entity/SocialType.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/global/oauth2/CustomOAuth2User.java
  src/main/java/backend/like_house/global/oauth2/OAuthAttributes.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/backend/like_house/global/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/backend/like_house/global/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/backend/like_house/global/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/backend/like_house/global/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/backend/like_house/global/redis/Redis.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
  src/main/java/backend/like_house/global/security/SecurityConfig.java
  src/main/java/backend/like_house/global/security/annotation/LoginUserResolver.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/backend/like_house/global/security/principal/CustomUserDetails.java
  src/main/java/backend/like_house/global/security/principal/CustomUserDetailsService.java
  src/main/java/backend/like_house/global/security/util/JWTUtil.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#64 ✨ Feature : 채팅 구현
  build.gradle
  src/main/java/backend/like_house/LikeHouseApplication.java
  src/main/java/backend/like_house/domain/chatting/controller/ChatController.java
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatConverter.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/converter/UserChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatDTO.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
  src/main/java/backend/like_house/domain/chatting/entity/UserChatRoom.java
  src/main/java/backend/like_house/domain/chatting/repository/ChatRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRepositoryImpl.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRoomRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/backend/like_house/domain/chatting/repository/UserChatRoomRepository.java
  src/main/java/backend/like_house/domain/chatting/service/ChatCommandService.java
  src/main/java/backend/like_house/domain/chatting/service/ChatQueryService.java
  src/main/java/backend/like_house/domain/chatting/service/ChatRoomCommandService.java
  src/main/java/backend/like_house/domain/chatting/service/ChatRoomQueryService.java
  src/main/java/backend/like_house/domain/chatting/service/UserChatRoomCommandService.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatCommandServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatQueryServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomCommandServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/UserChatRoomCommandCommandServiceImpl.java
  src/main/java/backend/like_house/domain/family_space/repository/FamilySpaceRepository.java
  src/main/java/backend/like_house/domain/user/repository/CustomUserRepository.java
  src/main/java/backend/like_house/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/backend/like_house/domain/user/repository/UserRepository.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/exception/ExceptionAdvice.java
  src/main/java/backend/like_house/global/error/handler/ChatException.java
  src/main/java/backend/like_house/global/error/handler/ChatRoomException.java
  src/main/java/backend/like_house/global/error/handler/UserChatRoomException.java
  src/main/java/backend/like_house/global/error/handler/UserException.java
  src/main/java/backend/like_house/global/socket/WebSocketConfig.java
  src/main/java/backend/like_house/global/socket/dto/ChattingDTO.java
  src/main/java/backend/like_house/global/socket/handler/CustomWebSocketExceptionHandler.java
  src/main/java/backend/like_house/global/socket/handler/JWTInterceptor.java
  src/main/java/backend/like_house/global/socket/handler/SocketUtil.java
  src/main/java/backend/like_house/global/socket/handler/TextHandler.java
  src/main/java/backend/like_house/global/socket/service/SocketService.java
  src/main/java/backend/like_house/global/validation/annotation/ExistChatRoom.java
  src/main/java/backend/like_house/global/validation/validator/ChatRoomExistValidator.java
  src/main/resources/application-database.yml
Labels: :sparkles: feature

#72 ✨ Feature : sock.js 추가
  src/main/java/backend/like_house/global/socket/WebSocketConfig.java
Labels: :sparkles: feature

#69 ✨ Feature : 게시글 기능 구현
  src/main/java/backend/like_house/domain/post/controller/CommentController.java
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/converter/CommentConverter.java
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/entity/Comment.java
  src/main/java/backend/like_house/domain/post/entity/Post.java
  src/main/java/backend/like_house/domain/post/repository/CommentRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostImageRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostLikeRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/repository/UserPostTagRepository.java
  src/main/java/backend/like_house/domain/post/service/CommentCommandService.java
  src/main/java/backend/like_house/domain/post/service/PostCommandService.java
  src/main/java/backend/like_house/domain/post/service/PostQueryService.java
  src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
  src/main/java/backend/like_house/domain/schedule/repository/ScheduleRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/ContactRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/CustomRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/RemoveUserRepository.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/handler/CommentException.java
  src/main/java/backend/like_house/global/error/handler/FamilySpaceException.java
  src/main/java/backend/like_house/global/error/handler/PostException.java
  src/main/java/backend/like_house/global/s3/S3Manager.java
Labels: :sparkles: feature

#76 ✨ Feature : put, get용 presigned url 추가
  src/main/java/backend/like_house/global/s3/controller/S3Controller.java
  src/main/java/backend/like_house/global/s3/dto/AwsDTO.java
  src/main/java/backend/like_house/global/s3/service/S3Service.java
Labels: :sparkles: feature
