Repository Like-House/BE, pull requests merged in 2024-08, with the labels that each got.

#78 ✨ Feature : 로그아웃 및 탈퇴 구현
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/auth/repository/AuthRepository.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/backend/like_house/global/security/util/JWTUtil.java
Labels: :sparkles: feature

#81 ✨ Feature : 알림 설정 기능 구현
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/domain/user/service/UserCommandService.java
  src/main/java/backend/like_house/domain/user/service/impl/UserCommandServiceImpl.java
Labels: :sparkles: feature

#84 🐛 Bug : header에 accessToken이 담기지 않는 문제
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :bug: bug

#86 ♻️ Refactor : 가족 앨범 조회 시 대표 이미지 하나만 반환
  src/main/java/backend/like_house/domain/post/repository/PostImageRepository.java
  src/main/java/backend/like_house/domain/post/service/impl/FamilyAlbumQueryServiceImpl.java
Labels: :recycle: refactor

#87 ✨ Feature : 사용자 정보 수정 기능 구현
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/domain/user/service/UserCommandService.java
  src/main/java/backend/like_house/domain/user/service/UserQueryService.java
  src/main/java/backend/like_house/domain/user/service/impl/UserCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :sparkles: feature

#88 ♻️ Refactor : 게시글 작성 시 이미지 업로드 방식 변경
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/service/PostCommandService.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
  src/main/java/backend/like_house/global/s3/S3Manager.java
Labels: :recycle: refactor

#92 ✨ Feature : 채팅, 채팅 방 관련 api 수정
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatConverter.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/backend/like_house/domain/chatting/service/ChatCommandService.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatCommandServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
  src/main/java/backend/like_house/domain/user/repository/CustomUserRepository.java
  src/main/java/backend/like_house/domain/user/repository/CustomUserRepositoryImpl.java
  src/main/java/backend/like_house/domain/user/service/UserQueryService.java
  src/main/java/backend/like_house/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/backend/like_house/global/socket/handler/SocketUtil.java
  src/main/java/backend/like_house/global/socket/service/SocketService.java
Labels: :sparkles: feature

#90 ✨ Feature : 가족 차단 기능 구현
  src/main/java/backend/like_house/domain/chatting/repository/ChatRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/UserChatRoomRepository.java
  src/main/java/backend/like_house/domain/notification/repository/NotificationRepository.java
  src/main/java/backend/like_house/domain/post/repository/CommentRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostLikeRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/repository/UserPostTagRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/ContactRepository.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementCommandServiceImpl.java
Labels: :sparkles: feature

#94 ♻️ Refactor : ERD 수정
  src/main/java/backend/like_house/domain/notification/entity/Notification.java
  src/main/java/backend/like_house/domain/schedule/entity/Schedule.java
  src/main/java/backend/like_house/domain/user/entity/User.java
Labels: :recycle: refactor

#98 ✨ Feature : 내가 속한 가족 공간 입장 기능 구현
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilySpaceConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilySpaceDTO.java
Labels: :sparkles: feature

#103 ♻️ Refactor : 소셜로그인 및 인증 과정 수정
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
Labels: :recycle: refactor

#104 ♻️ Refactor : 사진 DTO 교체
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
  src/main/java/backend/like_house/domain/family_space/controller/FamilyEmoticonController.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilyEmoticonDTO.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/s3/service/S3Service.java
  src/main/java/backend/like_house/global/validation/annotation/CheckImageKeyName.java
  src/main/java/backend/like_house/global/validation/validator/CheckImageKeyNameValidator.java
Labels: :recycle: refactor

#101 ♻️ Refactor : 가족 차단 시 데이터 유지
  src/main/java/backend/like_house/domain/chatting/repository/ChatRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/UserChatRoomRepository.java
  src/main/java/backend/like_house/domain/notification/repository/NotificationRepository.java
  src/main/java/backend/like_house/domain/post/repository/CommentRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostLikeRepository.java
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/repository/UserPostTagRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/ContactRepository.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementCommandServiceImpl.java
Labels: :recycle: refactor

#102 ♻️ Refactor : 가족 해제 관련 데이터 삭제
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/converter/UserManagementConverter.java
  src/main/java/backend/like_house/domain/user_management/dto/UserManagementDTO.java
  src/main/java/backend/like_house/domain/user_management/entity/RemoveUser.java
  src/main/java/backend/like_house/domain/user_management/repository/RemoveUserRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/querydsl/UserManagementQueryRepository.java
  src/main/java/backend/like_house/domain/user_management/repository/querydsl/impl/UserManagementQueryRepositoryImpl.java
  src/main/java/backend/like_house/domain/user_management/service/UserManagementCommandService.java
  src/main/java/backend/like_house/domain/user_management/service/UserManagementQueryService.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :recycle: refactor

#109 ♻️ Refactor : 유저 프로필 이미지 null 허용
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/user/entity/User.java
Labels: :recycle: refactor

#106 ✨ Feature : 일정 저장 시 작성자도 함께 저장
  src/main/java/backend/like_house/domain/schedule/converter/ScheduleConverter.java
Labels: :sparkles: feature

#116 ✨ Feature : 500에러 시 디스 코드 알림 기능 추가
  src/main/java/backend/like_house/global/error/exception/ExceptionAdvice.java
  src/main/java/backend/like_house/global/error/exception/alarmClient/dto/DiscordMessage.java
  src/main/java/backend/like_house/global/error/exception/alarmClient/service/DiscordClient.java
  src/main/resources/application-discord.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#111 ✨ Feature : 가족 이모티콘 관련 api 구현
  src/main/java/backend/like_house/domain/family_space/controller/FamilyEmoticonController.java
  src/main/java/backend/like_house/domain/family_space/converter/FamilyEmoticonConverter.java
  src/main/java/backend/like_house/domain/family_space/dto/FamilyEmoticonDTO.java
  src/main/java/backend/like_house/domain/family_space/repository/FamilyEmoticonRepository.java
  src/main/java/backend/like_house/domain/family_space/service/FamilyEmoticonCommandService.java
  src/main/java/backend/like_house/domain/family_space/service/FamilyEmoticonQueryService.java
  src/main/java/backend/like_house/domain/family_space/service/impl/FamilyEmoticonCommandServiceImpl.java
  src/main/java/backend/like_house/domain/family_space/service/impl/FamilyEmoticonQueryServiceImpl.java
  src/main/java/backend/like_house/domain/user/repository/UserRepository.java
  src/main/java/backend/like_house/global/error/handler/FamilyEmoticonException.java
Labels: :sparkles: feature

#114 ♻️ Refactor : presigned url 허용으로 변경
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :recycle: refactor

#120 ♻️ Refactor : JWT 예외처리 추가
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
Labels: :recycle: refactor

#124 ♻️ Refactor : socket jwt query param으로 수정
  src/main/java/backend/like_house/global/security/SecurityConfig.java
  src/main/java/backend/like_house/global/socket/handler/JWTInterceptor.java
Labels: :recycle: refactor

#127 :recycle: Refactor : 소켓 500에러 디스 코드 보내기 기능 추가
  src/main/java/backend/like_house/global/socket/WebSocketConfig.java
  src/main/java/backend/like_house/global/socket/handler/CustomWebSocketExceptionHandler.java
Labels: :recycle: refactor

#117 ♻️ Refactor : 유저 이미지 DTO 변경
  .DS_Store
  src/.DS_Store
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/converter/AuthConverter.java
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
  src/main/java/backend/like_house/domain/user/entity/User.java
Labels: :recycle: refactor

#121 ♻️ Refactor : Exception 분류
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/global/error/handler/UserManagementException.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
Labels: :recycle: refactor

#128 ✨ Feature : 이메일 인증 구현
  build.gradle
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/dto/EmailDTO.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/global/email/EmailConfig.java
  src/main/java/backend/like_house/global/email/EmailUtil.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
  src/main/resources/application-email.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#132 ♻️ Refactor : 채팅 api 통합
  src/main/java/backend/like_house/domain/chatting/controller/ChatController.java
  src/main/java/backend/like_house/domain/chatting/controller/ChatRoomController.java
  src/main/java/backend/like_house/domain/chatting/service/ChatQueryService.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatQueryServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
  src/main/java/backend/like_house/global/socket/service/SocketService.java
  src/main/java/backend/like_house/global/validation/annotation/CheckCursor.java
  src/main/java/backend/like_house/global/validation/validator/CheckCursorValidator.java
Labels: :recycle: refactor

#134 ♻️ Refactor : 에러 처리 service단으로 이동
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/domain/family_space/service/impl/FamilySpaceCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/service/UserQueryService.java
  src/main/java/backend/like_house/domain/user/service/impl/UserQueryServiceImpl.java
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/service/UserManagementCommandService.java
  src/main/java/backend/like_house/domain/user_management/service/UserManagementQueryService.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementQueryServiceImpl.java
Labels: :recycle: refactor

#133 ♻️ Refactor : 유저 관련 코드 정리
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/dto/EmailDTO.java
  src/main/java/backend/like_house/domain/auth/repository/AuthRepository.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/controller/UserController.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/backend/like_house/global/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/backend/like_house/global/redis/RedisUtil.java
Labels: :recycle: refactor

#136 ♻️ Refactor : SOCKJS 제거
  src/main/java/backend/like_house/global/socket/WebSocketConfig.java
Labels: :recycle: refactor

#138 🐛 Fix : 자기 자신 차단 불가능하도록 에러 추가
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/service/impl/UserManagementCommandServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :bug: bug

#140 🐛 Fix : 가족 공간 코드 validation 추가
  src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/validation/annotation/CheckFamilySpaceCode.java
  src/main/java/backend/like_house/global/validation/validator/CheckFamilySpaceCodeValidator.java
Labels: :bug: bug

#144 🐛 Fix : 별명, 메모 validation
  src/main/java/backend/like_house/domain/user_management/controller/UserManagementController.java
  src/main/java/backend/like_house/domain/user_management/entity/Custom.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/validation/annotation/CheckModifyFamilyData.java
  src/main/java/backend/like_house/global/validation/validator/CheckModifyFamilyDataValidator.java
Labels: :bug: bug

#143 🐛 Fix : Comment 작성 시 title 추가
  src/main/java/backend/like_house/domain/post/converter/CommentConverter.java
  src/main/java/backend/like_house/domain/post/dto/CommentDTO.java
Labels: :bug: bug

#147 ♻️ Refactor : 채팅 무한 스크롤 뒤집기
  src/main/java/backend/like_house/domain/chatting/converter/ChatConverter.java
  src/main/java/backend/like_house/global/socket/handler/SocketUtil.java
Labels: :recycle: refactor

#150 ♻️ Refactor : 내가 쓴 글 조회 무한 스크롤로 구현
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/service/PostQueryService.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
Labels: :recycle: refactor

#152 ♻️ Refactor : 날짜별 일정 조회 시 Cursor 디폴트 값 추가
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
Labels: :recycle: refactor

#154 ♻️ Refactor : 홈 (게시글 조회) 무한 스크롤로 구현
  src/main/java/backend/like_house/domain/post/controller/PostController.java
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/repository/PostRepository.java
  src/main/java/backend/like_house/domain/post/service/PostQueryService.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
Labels: :recycle: refactor

#156 ♻️ [Refactor] - 소셜로그인 이후 JWT를 쿠키로 반환하도록 수정
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
Labels: :recycle: refactor

#160 ♻️ Refactor - 일정 무한 스크롤 초기값 1L로 변경
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/schedule/service/impl/ScheduleCommandServiceImpl.java
  src/main/java/backend/like_house/domain/schedule/service/impl/ScheduleQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/handler/ScheduleException.java
Labels: :recycle: refactor

#158 ♻️ Refactor : 일반로그인 이후 JWT를 쿠키로 반환하도록 수정
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/backend/like_house/global/security/SecurityConfig.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/backend/like_house/global/security/util/JWTUtil.java
Labels: :recycle: refactor

#162 ✨ Feature : https 도메인 CORS setting
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :sparkles: feature

#145 ✨ Feature : 알림 기능 추가
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/backend/like_house/domain/auth/controller/AuthController.java
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/auth/repository/AuthRepository.java
  src/main/java/backend/like_house/domain/auth/service/AuthCommandService.java
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
  src/main/java/backend/like_house/domain/notification/controller/NotificationController.java
  src/main/java/backend/like_house/domain/notification/controller/NotificationRequestType.java
  src/main/java/backend/like_house/domain/notification/converter/NotificationConverter.java
  src/main/java/backend/like_house/domain/notification/dto/NotificationDTO.java
  src/main/java/backend/like_house/domain/notification/entity/Notification.java
  src/main/java/backend/like_house/domain/notification/repository/NotificationRepository.java
  src/main/java/backend/like_house/domain/notification/service/NotificationCommandService.java
  src/main/java/backend/like_house/domain/notification/service/NotificationQueryService.java
  src/main/java/backend/like_house/domain/notification/service/impl/NotificationCommandServiceImpl.java
  src/main/java/backend/like_house/domain/notification/service/impl/NotificationQueryServiceImpl.java
  src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
  src/main/java/backend/like_house/domain/user/entity/User.java
  src/main/java/backend/like_house/domain/user/repository/UserRepository.java
  src/main/java/backend/like_house/global/common/enums/NotificationType.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/error/handler/TokenException.java
  src/main/java/backend/like_house/global/firebase/FirebaseConfig.java
  src/main/java/backend/like_house/global/firebase/service/FCMQueryService.java
  src/main/java/backend/like_house/global/firebase/service/FcmService.java
  src/main/java/backend/like_house/global/socket/handler/SocketUtil.java
  src/main/java/backend/like_house/global/socket/service/SocketService.java
Labels: :sparkles: feature

#164 :bug: Fix : firebase config 생성 오류 해결
  .github/workflows/dev_deploy.yml
  src/main/java/backend/like_house/global/firebase/FirebaseConfig.java
  src/main/resources/application-firebase.yml
  src/main/resources/application.yml
Labels: :bug: bug

#166 ♻️ Refactor : 로그아웃 및 탈퇴시 쿠키 설정 변경
  src/main/java/backend/like_house/domain/auth/service/impl/AuthCommandServiceImpl.java
Labels: :recycle: refactor

#170 ♻️ Refactor : 소켓 연결 방식 수정
  src/main/java/backend/like_house/global/socket/handler/JWTInterceptor.java
Labels: :recycle: refactor

#172 ♻️ Refactor : 소셜로그인 프로필 이미지 keyname으로 저장
  build.gradle
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
  src/main/java/backend/like_house/global/oauth2/CustomOAuth2User.java
  src/main/java/backend/like_house/global/oauth2/OAuthAttributes.java
  src/main/java/backend/like_house/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/backend/like_house/global/s3/dto/AwsDTO.java
  src/main/java/backend/like_house/global/s3/service/S3Service.java
Labels: :recycle: refactor

#176 ♻️ Refactor : 사진 어노테이션 null 가능 옵션 추가
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/global/validation/validator/CheckImageKeyNameValidator.java
Labels: :recycle: refactor

#174 ♻️ Refactor : 알림 리턴 값 profile사진과 종류 추가
  src/main/java/backend/like_house/domain/notification/converter/NotificationConverter.java
  src/main/java/backend/like_house/domain/notification/dto/NotificationDTO.java
  src/main/java/backend/like_house/domain/notification/service/impl/NotificationQueryServiceImpl.java
Labels: :recycle: refactor

#180 ✨ Feature : 채팅 이미지 리턴 값 추가
  src/main/java/backend/like_house/global/socket/handler/SocketUtil.java
Labels: :sparkles: feature

#182 ♻️ Refactor : 사진 null 값 수정
  src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
  src/main/java/backend/like_house/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/entity/ChatRoom.java
Labels: :recycle: refactor

#183 ✨ Feature : 알림 설정 조회 기능
  src/main/java/backend/like_house/domain/user/controller/UserController.java
Labels: :sparkles: feature

#186 ♻️ Refactor : 유저 프로필 조회 response로 userId 추가
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
Labels: :recycle: refactor

#184 ✨ Feature : 한번에 받는 presigned url 기능 추가
  src/main/java/backend/like_house/global/s3/controller/S3Controller.java
  src/main/java/backend/like_house/global/s3/dto/AwsDTO.java
  src/main/java/backend/like_house/global/s3/service/S3Service.java
Labels: :sparkles: feature

#188 ♻️ Refactor : 게시글 작성 시 사진 첨부 선택으로 변경
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
Labels: :recycle: refactor

#190 ♻️ Refactor : 유저 프로필 response에 socialType 추가
  src/main/java/backend/like_house/domain/user/converter/UserConverter.java
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
Labels: :recycle: refactor

#192 ♻️ Refactor : 웹소켓 타임아웃 시간 늘리기
  .platform/nginx.conf
Labels: :recycle: refactor

#194 ♻️ Refactor : 댓글 title 삭제
  src/main/java/backend/like_house/domain/post/converter/CommentConverter.java
  src/main/java/backend/like_house/domain/post/dto/CommentDTO.java
  src/main/java/backend/like_house/domain/post/entity/Comment.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
Labels: :recycle: refactor

#196 ♻️ Refactor : 불필요한 어노테이션 삭제
  src/main/java/backend/like_house/domain/user/dto/UserDTO.java
Labels: :recycle: refactor

#198 ♻️ Refactor : 달별 일정 조회 페이지네이션 삭제
  src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
  src/main/java/backend/like_house/domain/schedule/converter/ScheduleConverter.java
  src/main/java/backend/like_house/domain/schedule/dto/ScheduleDTO.java
  src/main/java/backend/like_house/domain/schedule/repository/ScheduleRepository.java
  src/main/java/backend/like_house/domain/schedule/service/ScheduleQueryService.java
  src/main/java/backend/like_house/domain/schedule/service/impl/ScheduleQueryServiceImpl.java
Labels: :recycle: refactor

#200 ♻️ Refactor : 게시글, 댓글 현재 알림 상태 반환
  src/main/java/backend/like_house/domain/post/converter/CommentConverter.java
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/CommentDTO.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
Labels: :recycle: refactor

#202 ♻️ Refactor : accessToken 재발급 로직 수정
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
  src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/backend/like_house/global/security/util/JWTUtil.java
Labels: :recycle: refactor

#204 ♻️ Refactor : 채팅방 상대 이름 리턴
  .platform/nginx.conf
  src/main/java/backend/like_house/domain/chatting/converter/ChatRoomConverter.java
  src/main/java/backend/like_house/domain/chatting/dto/ChatRoomDTO.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRoomRepository.java
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRoomRepositoryImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomCommandServiceImpl.java
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
  src/main/java/backend/like_house/global/error/code/status/ErrorStatus.java
Labels: :recycle: refactor

#206 ♻️ Refactor : 웹소켓 타임아웃
  .platform/nginx.conf
Labels: :recycle: refactor

#208 ♻️ Refactor : 채팅방 null 일시 null return
  .platform/nginx/nginx.conf
  src/main/java/backend/like_house/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
Labels: :recycle: refactor

#212 ♻️ Refactor : 게시글 상세 조회 시 게시글 owner 추가
  src/main/java/backend/like_house/domain/post/converter/PostConverter.java
  src/main/java/backend/like_house/domain/post/dto/PostDTO.java
  src/main/java/backend/like_house/domain/post/service/impl/PostQueryServiceImpl.java
Labels: :recycle: refactor

#210 ♻️ Refactor : 웹소켓 시간 늘리기
  .platform/nginx/nginx.conf
Labels: :recycle: refactor

#214 ♻️ Refactor : 채팅 무한 스크롤 갯수 늘리기
  .platform/nginx.conf
  src/main/java/backend/like_house/domain/chatting/repository/CustomChatRepositoryImpl.java
Labels: :recycle: refactor

#216 ♻️ Refactor : nginx change
  .platform/nginx/nginx.conf
Labels: :recycle: refactor

#220 ✨ Feature : CORS 설정에 프론트 배포 주소 추가
  src/main/java/backend/like_house/global/security/SecurityConfig.java
Labels: :sparkles: feature

#218 ♻️ Refactor : nginx 수정
  .platform/nginx.conf
Labels: :recycle: refactor

#222 ♻️ Refactor : 소셜로그인 redirect 수정
  src/main/java/backend/like_house/global/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: :recycle: refactor
